[dns-server]
public = "dnspod"
private = "smartdns"

# cloud
[[devices]]
  system = "ubuntu"
  hardware = "guanxing"
  group = "cloud"
  desc = "观星云服务器"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "5.180.98.88"

[[devices]]
  system = "ubuntu"
  hardware = "coalcloud"
  group = "cloud"
  desc = "CoalCloud 服务器"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "45.87.103.35"

# lab
[[devices]]
  system = "openwrt"
  hardware = "sei12"
  group = "lab"
  desc = "软路由 OpenWRT"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "snmp:wan1_ad"

# lab
[[devices]]
  system = "pve"
  hardware = "sei12"
  group = "lab"
  desc = "PVE 虚拟化服务器"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.ansible]
  server = true

  [devices.extra.dns]
  public = "snmp:wan4_ad"
  private = "192.168.1.5"

[[devices]]
  system = "arch"
  hardware = "3090"
  group = "lab"
  desc = "ArchLinux 系统个人开发机"

  [devices.extra.ssh]
  ip = "192.168.1.105"
  user = "zrr"
  port = 22

  [[devices.extra.ssh.containers]]
  name = "main"
  user = "root"
  port = 10000

  [[devices.extra.ssh.containers]]
  name = "paddle"
  user = "root"
  port = 10001

  [devices.extra.dns]
  public = "snmp:wan2_ad"

[[devices]]
  system = "hass"
  hardware = "sei12"
  group = "lab"
  desc = "搭载 HomeAssistant 的 Debian 系统"

  [devices.extra.ssh]
  user = "zrr1999"
  port = 22

[[devices]]
  system = "omv"
  hardware = "sei12"
  group = "lab"
  desc = "omv 系统"

  [devices.extra.ssh]
  ip = "192.168.1.11"
  user = "root"
  port = 22

  [[devices.extra.ssh.containers]]
  name = "main"
  user = "zrr1999"
  port = 10000

# home
[[devices]]
  system = "arch"
  hardware = "7505"
  group = "home"
  desc = "ArchLinux 系统 7505 个人开发机"

  [devices.extra.ssh]
  user = "zrr"
  port = 22

  [devices.extra.dns]
  public = "snmp:adsl1"

[[devices]]
  system = "server"
  hardware = "7505"
  group = "home"
  desc = "7505 个人开发机用于运行各种服务的容器（ArchLinux）"

  [devices.extra.ssh]
  user = "zrr"
  port = 22

  [devices.extra.ansible]
  server = true

  [devices.extra.dns]
  public = "snmp:adsl3"

# shared
[[devices]]
  system = "ubuntu"
  hardware = "4090"
  group = "shared"
  desc = "实验室4卡 RTX4090 服务器"

  [devices.extra.ssh]
  user = "zhanrongrui"
  port = 22

  [devices.extra.dns]
  public = "4090.grifcc.top"
[[devices]]
  system = "ubuntu"
  hardware = "3090"
  group = "shared"
  desc = "实验室4卡 RTX3090 服务器"

  [devices.extra.ssh]
  user = "zhanrongrui"
  port = 22

  [devices.extra.dns]
  public = "3090.grifcc.top"
[[devices]]
  system = "ubuntu"
  hardware = "2080"
  group = "shared"
  desc = "实验室8卡 RTX2080Ti 服务器"

  [devices.extra.ssh]
  user = "zhanrongrui"
  port = 22

  [devices.extra.dns]
  public = "2080.grifcc.top"
