[dns-server]
public = "dnspod"
private = "smartdns"

# cloud
[[devices]]
  system = "ubuntu"
  hardware = "tencent"
  group = "cloud"
  desc = "腾讯云服务器"

  [devices.extra.ssh]
  user = "ubuntu"
  port = 22

  [devices.extra.ansible]
  server = true

  [devices.extra.dns]
  public = "1.15.231.43"

[[devices]]
  system = "ubuntu"
  hardware = "guanxing"
  group = "cloud"
  desc = "观星云服务器"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "5.180.98.88"

# lab
[[devices]]
  system = "openwrt"
  hardware = "sei12"
  group = "lab"
  desc = "软路由 OpenWRT"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "snmp:wan1_ad"

# lab
[[devices]]
  system = "pve"
  hardware = "sei12"
  group = "lab"
  desc = "PVE 虚拟化服务器"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.ansible]
  server = true

  [devices.extra.dns]
  public = "snmp:wan4_ad"
  private = "192.168.1.5"

[[devices]]
  system = "arch"
  hardware = "3090"
  group = "lab"
  desc = "ArchLinux 系统个人开发机"

  [devices.extra.ssh]
  ip = "192.168.1.105"
  user = "zrr"
  port = 22

  [[devices.extra.ssh.containers]]
  name = "dev-main"
  user = "root"
  port = 10000

  [[devices.extra.ssh.containers]]
  name = "dev-paddle"
  user = "root"
  port = 10001

  [devices.extra.dns]
  public = "snmp:wan2_ad"

[[devices]]
  system = "hass"
  hardware = "sei12"
  group = "lab"
  desc = "搭载 HomeAssistant 的 Debian 系统"

  [devices.extra.ssh]
  user = "zrr1999"
  port = 22

[[devices]]
  system = "ubuntu"
  hardware = "sei12"
  group = "lab"
  desc = "Ubuntu 系统个人开发机"

  [devices.extra.ssh]
  ip = "192.168.1.102"
  user = "zrr1999"
  port = 22

  [devices.extra.dns]
  public = "snmp:wan3_ad"

[[devices]]
  system = "omv"
  hardware = "sei12"
  group = "lab"
  desc = "omv 系统"

  [devices.extra.ssh]
  ip = "192.168.1.11"
  user = "root"
  port = 22

  [[devices.extra.ssh.containers]]
  name = "main"
  user = "zrr1999"
  port = 10000

# home

# shared
[[devices]]
  system = "ubuntu"
  hardware = "3090x5"
  group = "shared"
  desc = "实验室5卡 RTX3090 服务器"

  [devices.extra.ssh]
  user = "cv"
  port = 3090

  [devices.extra.dns]
  public = "302.grifcc.top"

[[devices]]
  system = "ubuntu"
  hardware = "guanxing"
  group = "shared"
  desc = "观星云服务器 2C4G"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "154.40.43.220"
