domain = "sixbones.dev"

[dns-server]
public = "dnspod"
private = "hosts"

# cloud
[[devices]]
  system = "ubuntu"
  hardware = "guanxing"
  group = "cloud"
  desc = "观星云服务器（香港，服务节点）"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "5.180.98.88"

[[devices]]
  system = "ubuntu"
  hardware = "clawcloud"
  group = "cloud"
  desc = "ClawCloud 服务器（东京，代理节点）"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "47.79.35.18"

[[devices]]
  system = "ubuntu"
  hardware = "coalcloud"
  group = "cloud"
  desc = "CoalCloud 服务器（香港，代理节点）"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.dns]
  public = "45.87.103.80"

# lab
[[devices]]
  system = "pve"
  hardware = "sei12"
  group = "lab"
  desc = "PVE 虚拟化服务器"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [devices.extra.ansible]
  server = true

  [devices.extra.dns]
  public = "snmp:wan4_ad"
  private = "192.168.1.5"

[[devices]]
  system = "hass"
  hardware = "sei12"
  group = "lab"
  desc = "HomeAssistant 智能家居系统（基于 Debian）"

  [devices.extra.ssh]
  user = "zrr1999"
  port = 22

[[devices]]
  system = "omv"
  hardware = "sei12"
  group = "lab"
  desc = "omv 个人存储系统（基于 Debian）"

  [devices.extra.ssh]
  user = "root"
  port = 22

  [[devices.extra.ssh.containers]]
  name = "main"
  user = "zrr1999"
  port = 10000

  [devices.extra.dns]
  private = "192.168.1.11"

# home
[[devices]]
  system = "arch"
  hardware = "7505"
  group = "home"
  desc = "ArchLinux 系统 7505 宿主机"

  [devices.extra.ssh]
  user = "zrr"
  port = 22

  [devices.extra.dns]
  public = "snmp:adsl1"
  private = "192.168.10.5"

[[devices]]
  system = "server"
  hardware = "7505"
  group = "home"
  desc = "7505 个人开发机用于运行各种服务的 ArchLinux 系统容器"

  [devices.extra.ssh]
  user = "zrr"
  port = 22

  [devices.extra.ansible]
  server = true

  [devices.extra.dns]
  public = "snmp:adsl3"
  private = "192.168.10.2"
