#!/bin/bash
install_by_installer() {
  # basic tools
  $1 zsh git lua yadm nexttrace
  # replacement of system tools
  $1 lsd sd dust ripgrep fd bottom procs duf httpie
  # other tools
  $1 pueue fzf progress atuin hyperfine
  $1 git-delta gitui zellij difftastic helix
}


install_by_brew() {
  # install Homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    (echo; echo "eval '$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)'") >> /etc/profile
    source /etc/profile
  fi

  brew install python pdm pre-commit
  brew install ast-grep micromamba github-cli
  ln -s $HOMEBREW_PREFIX/bin/zsh /bin/zsh

  if [[ "$OSTYPE" == "darwin"* ]]; then
    brew tap pot-app/homebrew-tap
    brew install --cask pot
  fi
}

install_by_pacman() {
  sudo pacman -S --noconfirm paru
  sudo pacman -S --noconfirm python python-pdm python-pre-commit
  paru -S --noconfirm ast-grep micromamba github-cli
}

config_zsh() {
  if ! command -v zi >/dev/null 2>&1; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/z-shell/zi-src/main/lib/sh/install.sh)" -- -i skip
    zsh -cl -- '(source $HOME/.zi.zsh && @zi-scheduler burst) || true'
  fi
}

if [[ $USER == "root" ]]; then
  echo "Please login as user and run this script again:"
  echo "  su - user"
  echo "  yadm clone --bootstrap https://github.com/zrr1999/dotfiles.git"
  exit
fi

if [[ -n "$GITHUB_ACTIONS" ]]; then
  echo "::group::installing packages"
fi
if [[ -f /etc/arch-release ]]; then
  echo "system type: ArchLinux, install by pacman"
  install_by_installer "sudo pacman -S --noconfirm"
  install_by_pacman
else
  echo "other system type, install by brew"
  install_by_installer "brew install"
  install_by_brew
fi
if [[ -n "$GITHUB_ACTIONS" ]]; then
  echo "::endgroup::"
fi

if [[ -n "$GITHUB_ACTIONS" ]]; then
  echo "::group::configuring zsh"
fi
config_zsh
if [[ -n "$GITHUB_ACTIONS" ]]; then
  echo "::endgroup::"
fi
