[dnspod]
domain = "bone6.top"
setter_name = "dnspod"
records_files = [
    "ddns.json",
    "sdns.json",
    "sdns-dnspod.json",
]
[cloudflare]
domain = "bone6.com"
setter_name = "cloudflare"
records_files = [
    "ddns.json",
    "sdns.json",
    "sdns-cf.json",
]

