"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$status\
$os\
$container\
$fill\
$username\
$hostname\
$time\
$line_break\
$shell\
$character"""

[character]
success_symbol = '[➜](bold green)'

[package]
disabled = true

[directory]
truncation_symbol = '.../'

[git_status]
ahead = "⇡$count"
diverged = "⇕⇡$ahead_count⇣$behind_count"
behind = "⇣$count"
modified = "!$count"
staged = "+$count"
deleted = "✘$count"
renamed = "»$count"
conflicted = "=$count"
untracked = "?$count"

[username]
style_user = "yellow bold"
format = " [$user@]($style)"

[hostname]
style = "yellow bold"
ssh_only = false
format = '[$hostname]($style) '
disabled = false

[time]
style = "bold green"
disabled = false
format = '[$time]($style) '
time_format = '%T'
utc_time_offset = '+8'
